export const SET_TRADING_PAIRS = 'SET_TRADING_PAIRS';
export const INIT_TRADING_PAIRS = 'INIT_TRADING_PAIRS';
export const FETCH_TRADING_PAIRS_FAILED = 'FETCH_TRADING_PAIRS_FAILED';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const INIT_PAIR_DETAILS = 'INIT_PAIR_DETAILS';
export const FETCH_PAIR_DETAILS_START = 'FETCH_PAIR_DETAILS_START';
export const FETCH_PAIR_DETAILS_SUCCESS = 'FETCH_PAIR_DETAILS_SUCCESS';
export const FETCH_PAIR_DETAILS_FAIL = 'FETCH_PAIR_DETAILS_FAIL';

export const GLOBAL_ERROR = 'GLOBAL_ERROR';
export const CLEAR_GLOBAL_ERROR = 'CLEAR_GLOBAL_ERROR';