export const SET_TRADING_PAIRS = 'SET_TRADING_PAIRS';
export const INIT_TRADING_PAIRS = 'INIT_TRADING_PAIRS';
export const FETCH_TRADING_PAIRS_FAILED = 'FETCH_TRADING_PAIRS_FAILED';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
